enum SvgImageId {
  menuHome('assets/svg/menu-home.svg'),
  menuTemplate('assets/svg/menu-template.svg'),
  menuProgress('assets/svg/menu-progress.svg'),
  menuExcercise('assets/svg/menu-excercise.svg'),

  menuSelectedHome('assets/svg/menu-home-selected.svg'),
  menuSelectedTemplate('assets/svg/menu-template-selected.svg'),
  menuSelectedProgress('assets/svg/menu-progress-selected.svg'),
  menuSelectedExcercise('assets/svg/menu-exercise-selected.svg'),
  uploadIcon('assets/svg/upload-icon.svg'),

  iconBlackStar('assets/svg/black-star.svg'),
  iconBack('assets/svg/icon-arrow-back.svg'),
  iconNext('assets/svg/icon-arrow-next.svg'),
  iconNextSmall('assets/svg/icon-arrow-next-small.svg'),
  iconDownArrow('assets/svg/icon-arrow-square-down.svg'),
  iconUpArrow('assets/svg/arrow-square-up.svg'),
  iconMiter('assets/svg/icon-miter.svg'),
  arrowLeft('assets/svg/icon-arrow-left.svg'),
  arrowRightButton('assets/svg/icon-arrow-right-button.svg'),
  arrowSquareDown('assets/svg/arrow-square-down.svg'),
  emptySquare('assets/svg/empty-square.svg'),
  favorite('assets/svg/favorite.svg'),
  tickSquare('assets/svg/tick-square.svg'),
  arrowRight('assets/svg/icon-arrow-right.svg'),
  arrowUp('assets/svg/icon-arrow-up.svg'),
  calendar('assets/svg/icon-calendar.svg'),
  info('assets/svg/icon-info.svg'),
  moreDots('assets/svg/more-dots.svg'),
  notification('assets/svg/icon-notification.svg'),
  eye('assets/svg/eye.svg'),

  filter('assets/svg/filter.svg'),
  search('assets/svg/search.svg'),
  aboutUs('assets/svg/about-us.svg'),
  age('assets/svg/age.svg'),
  diagram('assets/svg/diagram.svg'),

  iconDumble('assets/svg/icon-dumble.svg'),
  iconReps('assets/svg/icon-reps.svg'),
  iconTraining('assets/svg/icon-training.svg'),

  iconDumbleDark('assets/svg/icon-dumble-dark.svg'),
  iconRepsDark('assets/svg/icon-reps-dark.svg'),
  iconTrainingDark('assets/svg/icon-training-dark.svg'),

  simplification('assets/svg/simplification.svg'),
  simplificationDark('assets/svg/simplification-dark.svg'),
  iconShare('assets/svg/icon-share.svg'),
  checkGreenButton('assets/svg/check-green-button.svg'),
  crossRedButton('assets/svg/cross-red-button.svg'),

  measurment('assets/svg/measurement-scale.svg'),
  photo('assets/svg/photo.svg'),
  workoutList('assets/svg/workout-list.svg'),

  apple('assets/svg/apple.svg'),
  changePassword('assets/svg/change-password.svg'),
  contactUs('assets/svg/contact-us.svg'),
  country('assets/svg/country.svg'),
  DOB('assets/svg/date-of-birth.svg'),
  deleteAccount('assets/svg/delete-account.svg'),
  edit('assets/svg/edit.svg'),
  email('assets/svg/email.svg'),
  facebook('assets/svg/facebook.svg'),
  faq('assets/svg/faq.svg'),
  gender('assets/svg/gender.svg'),
  google('assets/svg/google.svg'),
  ifLogo('assets/svg/if.svg'),
  preferenceSuccess('assets/svg/preference_success.svg'),
  instagram('assets/svg/instagram.svg'),
  logout('assets/svg/logout.svg'),
  myAccount('assets/svg/my-account.svg'),
  fullName('assets/svg/full-name.svg'),
  nationality('assets/svg/nationality.svg'),
  phone('assets/svg/phone.svg'),
  privacyPolicy('assets/svg/privacy-policy.svg'),
  successCheck('assets/svg/success_check.svg'),
  zipCode('assets/svg/zip-code.svg'),
  preview('assets/svg/preview.svg'),
  delete('assets/svg/delete.svg'),
  logoutPop('assets/svg/logout-pop.svg'),
  customAccess('assets/svg/custom-access.svg'),
  futureWorkScheduling('assets/svg/future-work-scheduling.svg'),
  gymPhotoVault('assets/svg/gym-photo-vault.svg'),
  manageAccess('assets/svg/manage-access.svg'),
  myMeasurements('assets/svg/my-measurements.svg'),
  recievedAccess('assets/svg/recieved-access.svg'),
  workoutHistory('assets/svg/workout-history.svg'),
  appConfiguration('assets/svg/app-configuration.svg'),
  noExercise('assets/svg/no_exercise.svg'),
  plus('assets/svg/plus.svg'),
  minus('assets/svg/minus.svg'),
  clock('assets/svg/clock.svg'),
  close('assets/svg/close.svg'),
  remove('assets/svg/remove.svg'),
  faceId('assets/svg/face-id.svg'),
  fingure('assets/svg/fingure.svg'),
  strength('assets/svg/strength.svg'),
  addBordered('assets/svg/add-bordered.svg'),
  add('assets/svg/add.svg'),
  cancel('assets/svg/cancel.svg'),
  templatesType('assets/svg/templates-type.svg'),
  hourglass('assets/svg/hourglass.svg'),

  blueGraph('assets/svg/line-graph-blue.svg'),
  greenGraph('assets/svg/line-graph-green.svg'),
  orangeGraph('assets/svg/line-graph-orange.svg'),
  pinkGraph('assets/svg/line-graph-pink.svg'),
  purpleGraph('assets/svg/line-graph-purple.svg'),

  // home icons
  playCircle('assets/svg/play-circle.svg'),
  clockIcon('assets/svg/clock_icon.svg'),
  goalIcon('assets/svg/goal_icon.svg'),

  successCheckImage('assets/svg/success-check-image.svg');

  const SvgImageId(this.path);
  final String path;
}
